# Generated by Django 5.0.6 on 2026-03-11 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_d', '0002_fived_forced_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fivedbet',
            new_name='fived_bets_user_id_dea13c_idx',
            old_name='fived_bet_user_date_idx',
        ),
        migrations.AddIndex(
            model_name='fivedbet',
            index=models.Index(fields=['round', 'is_winner'], name='fived_bets_round_i_67f3e9_idx'),
        ),
    ]
