# Generated by Django 5.0.6 on 2026-03-11 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k3', '0002_k3_forced_dice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='k3bet',
            new_name='k3_bets_user_id_b63c8f_idx',
            old_name='k3_bet_user_date_idx',
        ),
        migrations.AddIndex(
            model_name='k3bet',
            index=models.Index(fields=['round', 'is_winner'], name='k3_bets_round_i_1d7314_idx'),
        ),
    ]
