# Generated by Django 5.0.6 on 2026-03-11 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_deposit_withdraw'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='depositrequest',
            new_name='deposit_req_wallet__205337_idx',
            old_name='dep_wallet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_wallet__efd4a5_idx',
            old_name='tx_wallet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_referen_c33c6b_idx',
            old_name='tx_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawrequest',
            new_name='withdraw_re_wallet__6dce19_idx',
            old_name='wd_wallet_date_idx',
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SIGNUP_BONUS', 'Signup Bonus'), ('ADMIN_CREDIT', 'Admin Credit'), ('ADMIN_DEBIT', 'Admin Debit'), ('BET_PLACED', 'Bet Placed'), ('BET_WON', 'Bet Won'), ('BET_REFUND', 'Bet Refund'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], default='ADMIN_CREDIT', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
