# Generated by Django 5.0.6 on 2026-03-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wingo', '0002_wingo_modes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wingoround',
            options={'ordering': ['-round_number', 'mode']},
        ),
        migrations.RemoveIndex(
            model_name='wingoround',
            name='wingo_round_num_idx',
        ),
        migrations.RenameIndex(
            model_name='wingobet',
            new_name='wingo_bets_user_id_ea21b9_idx',
            old_name='wingo_bet_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='wingobet',
            new_name='wingo_bets_round_i_32fb0b_idx',
            old_name='wingo_bet_round_winner_idx',
        ),
        migrations.RenameIndex(
            model_name='wingoround',
            new_name='wingo_round_mode_3d471b_idx',
            old_name='wingo_mode_round_idx',
        ),
        migrations.RenameIndex(
            model_name='wingoround',
            new_name='wingo_round_mode_454920_idx',
            old_name='wingo_mode_status_idx',
        ),
    ]
